_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  ROI_HEADS:
    NAME: "RepLossROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    REPULSION_LOSS:
      REP_GT_FACTOR: 0.5 # 'alpha' in paper
      REP_BOX_FACTOR: 0.5 # 'beta' in paper
      REP_GT_SIGMA: 0.9 # for smooth_ln
      REP_BOX_SIGMA: 0.1 # for smooth_ln
      D2_NORMALIZE: True # False to normalize like the paper; see RepLossFastRCNNOutputs
VERSION: 2